CREATE TABLE ORDERS(
  id VARCHAR(255) PRIMARY KEY,
  user_id VARCHAR(255),
  name VARCHAR(255),
  address VARCHAR(255) NOT NULL,
  phone VARCHAR(255) NOT NULL,
  order_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES USERS(id),
  total_price FLOAT
);


CREATE TABLE ORDERITEMS(
  id VARCHAR(255) PRIMARY KEY,
  order_id VARCHAR(255) ,
  product_id VARCHAR(255),
  quantity INTEGER,
  amount FLOAT,
  FOREIGN KEY (order_id) REFERENCES ORDERS(id),
  FOREIGN KEY (product_id) REFERENCES PRODUCTS(id)
);