CREATE TABLE PAYMENTS(
  order_id VARCHAR(255) PRIMARY KEY,
  user_id VARCHAR(255),
  pay_type VARCHAR(255),
  amount FLOAT,
  FOREIGN KEY (order_id) REFERENCES ORDERS(id),
  time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES USERS(id)
);